# Para trocar os arquivos troque o name, URL e INPUT_FILE_PATH
cloud-comp-job:
  name: job-rules
  login: alexandrevieira
  image: albatis/generator-rules-processor:latest
  resources:
    memory: 2G
  environments:
    URL: "https://homepages.dcc.ufmg.br/~cunha/hosted/cloudcomp-2023s2-datasets/2023_spotify_ds1.csv"
    MIN_SUPPORT: "0.04"
    INPUT_FILE_PATH: /mnt/2023_spotify_ds1.csv
  commandInitContainer: "rm -f /mnt/*; wget --no-check-certificate $URL -P /mnt;"
  volumes:
    - name: project2-pv
      storageClassName: default-storage-class-alexandrevieira
      size: 1Gi
      path: /mnt
      hostPath: /home/alexandrevieira/project2-pv
      accessMode: ReadWriteMany
      ignore: true
      ignorePVC: true